name: poject_qr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/input_1.png
    - assets/images/menu_11.png
    - assets/images/home_05.png
    - assets/images/input_11.png
    - assets/images/configuration_1.png
    - assets/images/stock_1.png
    - assets/images/stock_11.png
    - assets/images/delete_1.png
    - assets/images/add_11.png
    - assets/images/loupe_1.png
    - assets/images/up_selling_1.png
    - assets/images/add_1.png
    - assets/images/frame_34665301.jpeg
    - assets/images/doctor_png_images_1.png
    - assets/images/frame_3466530.jpeg
    - assets/images/play_21.png
    - assets/images/up_arrow_1.png
    - assets/images/play_31.png
    - assets/images/camera_1.png
    - assets/images/gallery_11.png
